### ISSUE TITLE
Kerberos krb5.conf.template not found

### ISSUE THREAD

**Issue by shad00m** [RotherOSS/otobo-docker#150]
Hi,

I've set up a fresh rel-11_0 docker installation which was running fine with the ".docker_compose_env_https" env file
Following the Kerberos tutorial on the dot [here](https://doc.otobo.org/manual/installation/11.0/en/content/sso-kerberos.html)  but it always stops with the following error:

```
otobo-nginx-1    | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
otobo-nginx-1    | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
otobo-nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
otobo-nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/21-envsubst-on-krb5-conf.sh
otobo-nginx-1    | /docker-entrypoint.d/21-envsubst-on-krb5-conf.sh: 25: cannot open /etc/nginx/config/template-custom/../../kerberos/templates/krb5.conf.template: No such file
otobo-nginx-1 exited with code 2
```

/etc/nginx/config/template-custom/../../kerberos/templates/krb5.conf.template would resolve to /etc/nginx/kerberos/templates/krb5.conf.template 

In the Container it seems to be available:
ls
krb5.conf.template
pwd
/etc/nginx/kerberos/templates

My config looks like this:
```
root@otobo-kerberos:/opt/otobo-docker# docker compose config
name: otobo
services:
  daemon:
    cap_drop:
    - ALL
    command:
    - daemon
    depends_on:
      web:
        condition: service_started
        required: true
    healthcheck:
      test:
      - CMD-SHELL
      - ./bin/otobo.Daemon.pl status | grep 'Daemon running'
    image: rotheross/otobo:latest-11_0
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: 10m
    networks:
      default: null
    restart: always
    volumes:
    - type: volume
      source: opt_otobo
      target: /opt/otobo
      volume: {}
  db:
    cap_add:
    - CAP_SYS_CHROOT
    cap_drop:
    - ALL
    command:
    - --max-allowed-packet=136314880
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --innodb-log-file-size=268435456
    - --query-cache-size=33554432
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
    healthcheck:
      test:
      - CMD-SHELL
      - mysqladmin -h db --user=root --password='PASSWORD' ping
    image: mariadb:10.5
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: 10m
    networks:
      default: null
    restart: always
    user: mysql:mysql
    volumes:
    - type: volume
      source: mariadb_data
      target: /var/lib/mysql
      volume: {}
  elastic:
    cap_add:
    - CAP_SYS_CHROOT
    - CAP_SETUID
    - CAP_SETGID
    cap_drop:
    - ALL
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    healthcheck:
      test:
      - CMD-SHELL
      - curl -s -f http://localhost:9200/_cat/health
    image: rotheross/otobo-elasticsearch:latest-11_0
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: 10m
    networks:
      default: null
    restart: always
    volumes:
    - type: volume
      source: elasticsearch_data
      target: /usr/share/elasticsearch/data
      volume: {}
  nginx:
    cap_add:
    - CAP_SYS_CHROOT
    - CAP_CHOWN
    - CAP_DAC_OVERRIDE
    - CAP_SETGID
    - CAP_SETUID
    cap_drop:
    - ALL
    depends_on:
      web:
        condition: service_started
        required: true
    environment:
      NGINX_ENVSUBST_TEMPLATE_DIR: /etc/nginx/config/template-custom
      OTOBO_NGINX_KERBEROS_ADMIN_SERVER: domain.local
      OTOBO_NGINX_KERBEROS_DEFAULT_DOMAIN: domain.local
      OTOBO_NGINX_KERBEROS_KDC: domain.local
      OTOBO_NGINX_KERBEROS_REALM: domain.LOCAL
      OTOBO_NGINX_KERBEROS_SERVICE_NAME: HTTP/otobo-kerberos.domain.local
      OTOBO_NGINX_SSL_CERTIFICATE: /etc/nginx/ssl/ssl-cert.crt
      OTOBO_NGINX_SSL_CERTIFICATE_KEY: /etc/nginx/ssl/ssl-key.key
      OTOBO_NGINX_WEB_HOST: web
      OTOBO_NGINX_WEB_PORT: "5000"
      OTOBO_WEB_HTTPS_PORT: ""
    healthcheck:
      test:
      - CMD-SHELL
      - service nginx status || exit 1
    image: rotheross/otobo-nginx-kerberos-webproxy:latest-11_0
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 0.0.0.0
      target: 8443
      published: "443"
      protocol: tcp
    - mode: ingress
      host_ip: 0.0.0.0
      target: 8080
      published: "80"
      protocol: tcp
    restart: always
    volumes:
    - type: volume
      source: otobo_nginx_ssl
      target: /etc/nginx/ssl
      volume: {}
    - type: bind
      source: /opt/otobo-docker/nginx-conf/krb5.keytab
      target: /etc/krb5.keytab
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /opt/otobo-docker/nginx-conf/krb5.conf
      target: /etc/krb5.conf
      read_only: true
      bind:
        create_host_path: true
  redis:
    cap_drop:
    - ALL
    healthcheck:
      test:
      - CMD-SHELL
      - redis-cli ping
    image: redis:6.0-alpine
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: 10m
    networks:
      default: null
    restart: always
    user: redis:redis
    volumes:
    - type: volume
      source: redis_data
      target: /data
      volume: {}
  web:
    cap_drop:
    - ALL
    command:
    - web
    depends_on:
      db:
        condition: service_started
        required: true
      elastic:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    healthcheck:
      test:
      - CMD-SHELL
      - curl -s -f http://localhost:5000/robots.txt
    image: rotheross/otobo:latest-11_0
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: 10m
    networks:
      default: null
    restart: always
    volumes:
    - type: volume
      source: opt_otobo
      target: /opt/otobo
      volume: {}
networks:
  default:
    name: otobo_default
volumes:
  elasticsearch_data:
    name: otobo_elasticsearch_data
  mariadb_data:
    name: otobo_mariadb_data
  opt_otobo:
    name: otobo_opt_otobo
  otobo_nginx_ssl:
    name: otobo_nginx_ssl
    external: true
  redis_data:
    name: otobo_redis_data

```
