### ISSUE TITLE
Add tags to the Docker container logs

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo-docker#48]
Michael suggested this on the OTOBO Community Forum in the thread https://otobo.de/en/forums/topic/docker-logs-auf-lokalem-host-unter-centos8/.
Adding tags to the logs written by the containers can be very useful. E.g. for configuring dedicated logfiles for each service. Michael suggests:
```

  # service db
   logging:
      options:
        tag: "otobo_db_1"
 # service web
    logging:
      options:
        tag: "otobo_web_1"

```
I would suggest to remove the '_1' as there can be multiple containers per service. IMHO this can be done already for OTOBO 10.0.10.
